language: python
python:
  - "2.7"
sudo: required
install:
  - pip install pep8
  - pip install -r requirements.txt

script: veda_worker

# testing until totally rebuilt
script:
 - python tests/test_api_connect.py
# - python tests/test_asset_connect.py
 - python tests/test_build.py
# - python tests/test_encode.py
# - python tests/test_end_to_end.py
# - python tests/test_intake.py
# - python tests/test_node_connect.py
# - python tests/test_video_abstraction.py
 - pep8
