language: python
python:
  - "2.7"
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

install:
  - pip install pep8
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script: veda_worker

script:
 - python tests/test_api_connect.py
 - python tests/test_build.py
 - nosetests veda_worker/tests/test_video_images.py
# - python tests/test_asset_connect.py
# - python tests/test_encode.py
# - python tests/test_end_to_end.py
# - python tests/test_intake.py
# - python tests/test_node_connect.py
# - python tests/test_video_abstraction.py
 - pep8
