---

#-----------------------------------------------------
# This is a configable YAML file for instance defaults
#-----------------------------------------------------
#----
# Encode Commands
#----
ffmpeg_compiled: ''
ffmpeg_compiled: ''

#-----
# AWS
#-----
# AWS Storage Information
aws_access_key: ''
aws_secret_key: ''
aws_storage_bucket: ''
# AWS Delivery Information
aws_deliver_access_key: ''
aws_deliver_secret_key: ''
aws_deliver_bucket: ''

#-----
# Node commands
#-----
celery_app_name: ''
celery_queue: ''
rabbitmq_user: ''
rabbitmq_pass: ''
rabbitmq_broker: ''

#-----
# API
#-----
# VEDA Information
veda_token_url: ''
veda_auth_url: ''
veda_api_url: ''
veda_client_id: ''
veda_secret_key: ''

# VAL Information
val_client_id: ''
val_secret_key: ''
val_token_url: ''
val_api_url: ''
val_username: ''
val_password: ''

...